include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    avoid_positional_boolean_parameters: false
    cascade_invocations: false
    one_member_abstracts: false

analyzer:
  errors:
    invalid_annotation_target: ignore
